[default]
bucket_name = "kalschi_etl_2"
allow_trailing_spaces = true
allow_trailing_nulls = true

[project]
id = "customermod-genai-sa"
location = "us-central1"
endpoint = "us-central1-aiplatform.googleapis.com"

[gcs]
bucket_name = "kalschi_etl_2"

[models]
gemini = "gemini-1.0-pro-vision-001"
llm = "text-bison@002"

[vectors]
index_path = "projects/290493077924/locations/us-central1/indexes/2770527409437409280"
endpoint_id = "6560869445823102976"
deployed_index = "flipkart_partial_index_mul_1709050838862"
number_of_neighbors = 7

[big_query]
prefix = "customermod-genai-sa.kalschi_products"
product_table = "customermod-genai-sa.kalschi_products.master-final-product-catalog"
product_id_column = "id"
product_category_column_list = ["c0_name", "c1_name", "c2_name", "c3_name"]
product_attributes_column = "attributes"
product_description_column = "description"
product_category_allow_trailing_nulls = true

[category]
filter = ["L0", "L1", "L2", "L3"]
depth = 4

[test]
product_id = "dbdac18a8ee5a8a48238b9685c96e90a"
category = "Watches"
description = "Timewel 1100-N1949_S Analog Watch - For Women - Buy Timewel 1100-N1949_S Analog Watch - For Women 1100-N1949_S Online at Rs.855 in India Only at Flipkart.com. - Great Discounts, Only Genuine Products, 30 Day Replacement Guarantee, Free Shipping. Cash On Delivery!"
gcs_image = "gs://genai-product-catalog/flipkart_20k_oct26/dbdac18a8ee5a8a48238b9685c96e90a_0.jpg"
image_url = "http://img5a.flixcart.com/image/watch/t/p/r/1100-n1949-s-timewel-1100x1360-imaefy3pr4cwvduj.jpeg"